networks:
  loki:
    driver: bridge
services:
  loki:
    build:
      context: ./loki
      dockerfile: Dockerfile
    ports:
      - "3100:3100"
    networks:
      - loki
  pythonapp:
    build:
      context: ./services.user
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    networks:
      - loki
  grafana:
    build:
        context: ./Grafana
        dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - loki
  terraform:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
    privileged: true
  jenkins:
    build:
      context: ./Jenkins
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "50000:50000"
    networks:
      - loki